language: java

jdk:
  - openjdk14

#sudo: false

env:
  global:
  - CODECOV_TOKEN='0597875b-a177-4814-ad6b-59468692e461'


# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - glavstroi_e@mail.ru
    on_success: never # default: change
    on_failure: always # default: always

# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres